rootProject.name = "ArchitectureTemplate"
include(":app")
include(":domain:entity:core")
include(":domain:entity:auth")
include(":domain:service:core")
include(":domain:service:auth")
include(":presentation:viewModel:core")
include(":presentation:viewModel:auth")
include(":dataStore:gateway")
include(":dataStore:gateway:server")
include(":dataStore:gateway:local")
include(":dataStore:gateway:sdk")
include(":dataStore:repository")
include(":dataStore:repository:core")
include(":dataStore:repository:auth")
